package de.uniks.vs.jalica.autogenerated.plans.behaviour.utilityfunctions;

import de.uniks.vs.jalica.common.UtilityFunction;
import de.uniks.vs.jalica.unknown.BasicUtilityFunction;
import de.uniks.vs.jalica.unknown.DefaultUtilityFunction;
import de.uniks.vs.jalica.unknown.Plan;

public class UtilityFunction1413200862180 extends BasicUtilityFunction {

    @Override
    public UtilityFunction getUtilityFunction(Plan plan) {
        /*PROTECTED REGION ID(1413200862180) ENABLED START*/

        UtilityFunction defaultFunction = new DefaultUtilityFunction(plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }
}
