package de.uniks.vs.jalica.autogenerated.plans.behaviour;

import de.uniks.vs.jalica.autogenerated.plans.behaviour.transitions.*;
import de.uniks.vs.jalica.behaviours.ConditionCreator;
import de.uniks.vs.jalica.behaviours.DummyTransitionCondition;
import de.uniks.vs.jalica.engine.BasicCondition;
import de.uniks.vs.jalica.common.utils.CommonUtils;

/**
 * Created by alex on 13.07.17.
 */
public class TestConditionCreator extends ConditionCreator {

    public TestConditionCreator() { }

    public BasicCondition createConditions(long conditionConfId) {

        if (conditionConfId == 1413201227586l) {
            return new TransitionCondition1413201227586();
        }

        else if (conditionConfId == 1413201389955l) {
            return new TransitionCondition1413201389955();
        }

        else if (conditionConfId == 1413201052549l) {
            return new TransitionCondition1413201052549();
        }

        else if (conditionConfId == 1413201367990l) {
            return new TransitionCondition1413201367990();
        }

        else if (conditionConfId == 1413201370590l) {
            return new TransitionCondition1413201370590();
        }

        else {
//            System.out.println("ConditionCreator: Unknown condition requested: " + conditionConfId);
            CommonUtils.aboutError("ConditionCreator: Unknown condition requested: " + conditionConfId);
            return new DummyTransitionCondition();
        }
    }
}
