package de.uniks.vs.jalica.supplementary;

import de.uniks.vs.jalica.engine.AlicaEngine;
import de.uniks.vs.jalica.engine.BasicBehaviour;

/**
 * Created by alex on 01.08.17.
 */

//TODO: move to autogenerated
public abstract class DomainBehaviour extends BasicBehaviour {

    protected String agentName;
    protected SystemConfig systemConfig;
//    protected double maxTranslation;
    protected int ownID;

    public DomainBehaviour(String name, AlicaEngine ae) {
        super(name);
        this.systemConfig = ae.getSystemConfig();
        this.agentName = ae.getAgentName();
        this.ownID = systemConfig.getOwnAgentID();
    }

    public String getAgentName() {
        return agentName;
    }
}
